-- Disable RLS on all tables
ALTER TABLE public.experimentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resultados DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.metricas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_experimento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subtipos_experimento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.anexos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.comentarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cache_oraculo DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.canal_tipo_sugestao DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.convites DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.insights_processados DISABLE ROW LEVEL SECURITY;