// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zowjxaschkqivrltpfmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvd2p4YXNjaGtxaXZybHRwZm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTQzNzMsImV4cCI6MjA2OTYzMDM3M30.93njseLeE9y7KvAZFiPBL_Az4Kt38rAByifwVfVyi6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});